### ISSUE TITLE
Buy web hosting for CMC

### ISSUE THREAD

**Issue by lysender** [lysender/criticizemycode#15]
To buy a web hosting account for the CMC project.

**Comment by copongcopong** [comment]
No need to buy hosting, I have unlimited hosting.

**Comment by copongcopong** [comment]
I will research on how to give you access to SSH using a certificate on my bluehost account.

**Comment by lysender** [comment]
Wow, thanks sir Earl. 

Great news!

**Comment by lysender** [comment]
Off to Pagodabox!
